spring:
  application.name: demo-entity-status

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5433/demo}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/v1_0
